const data = {
  products: [
    {
      _id: "1",
      image: "/assets/images/image13.png",
      title: "Virtual Reality Helmet Zero spin",
      Category:"Internet Services",
      new_release: true,
      specification: "High Speed Router",
      quantity:10,
      rating: 5,
      price: "3600",
      date:"11/13/1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2",
      description:"gvcwvcqxjxbqsx",
      availability:"Available"
    },
    {
      _id: "2",
      image: "/assets/images/image15.png",
      Category:"Router",
      title: "Mega Speed Router",
      new_release: false,
      specification: "High Speed Router with something",
      rating: 4,
      price: "3,600.00 Kz",
      quantity:10,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"

    },
    {
      _id: "3",
      image: "/assets/images/image19.png",
      title: "Additional Boost Router",
      Category:"Router",
      new_release: false,
      specification: "High Speed Router",
      rating: 5,
      price: "86$",
      quantity:10,
      date:"29-11-1993",
      discountPrice:"2000",
      offer:'10% discount',
      warranty:"3 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "4",
      image: "/assets/images/image20.png",
      title: "Virtual Reality Helmet Zero spin",
      new_release: true,
      specification: "High Speed Router",
      rating: 5,
      Category:"Router",
      price: "3,600.00 Kz",
      quantity:10,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "5",
      image: "/assets/images/image13.png",
      title: "Mega Speed Router",
      new_release: false,
      specification: "High Speed Router with something",
      rating: 4,
      price: "3,600.00 Kz",
      Category:"Router",
      quantity:6,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "6",
      image: "/assets/images/image15.png",
      title: "Additional Boost Router",
      new_release: false,
      Category:"Router",
      specification: "High Speed Router",
      rating: 5,
      price: "86$",
      quantity:20,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "7",
      image: "/assets/images/image19.png",
      title: "Virtual Reality Helmet Zero spin",
      new_release: true,
      Category:"Router",
      specification: "High Speed Router",
      rating: 5,
      price: "3,600.00 Kz",
      quantity:40,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"no"
    },
    {
      _id: "8",
      image: "/assets/images/image20.png",
      title: "Mega Speed Router",
      new_release: false,
      Category:"Router",
      specification: "High Speed Router with something",
      rating: 4,
      price: "3,600.00 Kz",
      quantity:50,
      date:"13-11-1993",
      discountPrice:"5000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "9",
      image: "/assets/images/image13.png",
      title: "High Boost Router",
      new_release: false,
      Category:"Router",
      specification: "High Speed Router",
      rating: 5,
      quantity:10,
      price: "86$",
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "10",
      image: "/assets/images/image13.png",
      title: " Router",
      new_release: false,
      Category:"Router",
      specification: "High Speed Router",
      rating: 5,
      quantity:100,
      price: "86$",
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "11",
      image: "/assets/images/tv.png",
      title: "one plus smart Tv",
      new_release: false,
      Category:"Televion",
      specification: "smart Tv with 558px graphics",
      rating: 5,
      quantity:10,
      price: "5000$",
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes"
    },
    {
      _id: "12",
      image: "/assets/images/phone2.jpg",
      title: "samsung 5g Mobile",
      new_release: false,
      Category:"Mobiles",
      specification: "12Gb ram 64 Gb memory",
      rating: 5,
      quantity:0,
      date:"13-11-1993",
      discountPrice:"1000",
      offer:'-',
      warranty:"2 years",
      description:"gvcwvcqxjxbqsx",
      availability:"yes",
      price: "500$",
    },
    

  ],

  categories: [
    {
      _id: "1",
      image: "/assets/images/internet.png",
      title: "Internet Services",
      quantity:"5",
      link:"internet-services",
      product:'something',
      description:"jwkcjwdcbw"
    },
    {
      _id: "2",
      image: "/assets/images/network.png",
      title: "Network Equipment",
      quantity:"10",
      link:'network-equipments',
      product:'something',
      description:"jwkcjwdcbw"
    },
    {
      _id: "3",
      image: "/assets/images/cpe.png",
      title: "CPE'S",
      link:"cpe",
      quantity:"100",
      product:'something', description:"jwkcjwdcbw"
    },
    {
      _id: "4",
      image: "/assets/images/otherproducts.png",
      title: "Other Products",
      link:"otherproducts",
      quantity:"120",
      product:'something',
      description:"jwkcjwdcbw"
    },
    {
      _id: "5",
      image: "/assets/images/promotions.png",
      title: "Promotions",
      link:"promotions",
      quantity:"50",
      product:'something',
      description:"jwkcjwdcbw"
    },
  ],

  static:[
    {
      id:"1",
      image: "/assets/images/cpe1.png",
      title:"Home Banner",
      subheading:" hdcgwdgchdwgogeocqec",
      description: "hdcgwdgchdwgogeocqec",
      link:"/internet-services"
    },
    {
      id:"2",
      image: "/assets/images/cpe2.png",
      title:"Home Banner",
      subheading:" hdcgwdgchdwgogeocqec",
      description: "hdcgwdgchdwgogeocqec",
      link:"/internet-services"
    }
  ]
};
export default data;
